# Generated by Django 6.1 on 2026-08-08 11:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('size', models.CharField(choices=[('tiny', 'Миниатюрная'), ('small', 'Маленькая'), ('medium', 'Средняя'), ('large', 'Крупная')], max_length=6, verbose_name='Размер')),
                ('friendliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Дружелюбие')),
                ('trainability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Обучаемость')),
                ('shedding_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Интенсивность линьки')),
                ('exercise_needs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Потребность в активности')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст')),
                ('gender', models.CharField(max_length=60, verbose_name='Пол')),
                ('color', models.CharField(max_length=120, verbose_name='Цвет')),
                ('favorite_food', models.CharField(max_length=250, verbose_name='Любимая еда')),
                ('favorite_toy', models.CharField(max_length=250, verbose_name='Любимая игрушка')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'Собаки',
                'default_related_name': 'dogs',
            },
        ),
    ]
