DOG_NAME_CHAR_MAX_LENGTH = 120
DOG_GENDER_CHAR_MAX_LENGTH = 60
DOG_COLOR_CHAR_MAX_LENGTH = 120
DOG_FAVORITE_FOOD_CHAR_MAX_LENGTH = 250
DOG_FAVORITE_TOY_CHAR_MAX_LENGTH = 250

BREED_MIN_INTEGER = 1
BREED_MAX_INTEGER = 5
BREED_NAME_CHAR_MAX_LENGTH = 120
